name = "FixedEffects"
uuid = "c8885935-8500-56a7-9867-7708b20db0eb"
version = "0.2.0"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "â‰¥ 1.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
CuArrays = "3a865a2d-5b23-5a0f-bc46-62713ec82fae"

[targets]
test = ["Test"]
